name: API Tests with Newman

on:
  push:
    branches: [ "main" ]

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Newman and Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run API Tests and Generate Report
        run: |
          newman run collections/DemoQA_API_Automation.postman_collection.json \
          -e collections/DemoQA_Env.postman_environment.json \
          --reporters cli,htmlextra \
          --reporter-htmlextra-export ./index.html \
          --suppress-exit-code

      - name: Upload HTML Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: ./index.html

      - name: Deploy Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages