name: API Tests with Newman

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Newman
        run: npm install -g newman

      - name: Install HTML Extra Reporter
        run: npm install -g newman-reporter-htmlextra

      - name: Run API Tests with Newman
        run: |
          mkdir -p reports
          newman run collections/DemoQA_API_Automation.postman_collection.json \
            -e collections/DemoQA_Env.postman_environment.json \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export reports/index.html \
            --suppress-exit-code

      - name: Upload HTML Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: newman-html-report
          path: reports/index.html

      - name: Deploy Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          keep_files: true
          allow_empty_commit: true
          force_orphan: true
          enable_jekyll: false
          exclude_assets: ''
          destination_dir: .
          full_commit_message: "Deploy Newman HTML Report"
